// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddDebtorMerchantKey(arg1:number,arg2:string):Promise<void>;

export function AddDebtorTransaction(arg1:number,arg2:string,arg3:number,arg4:string):Promise<void>;

export function CategorizeByMerchant(arg1:string,arg2:number):Promise<number>;

export function CreateCategory(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean):Promise<models.Category>;

export function CreateDebtor(arg1:string,arg2:string,arg3:string):Promise<models.Debtor>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteCategoryRule(arg1:number):Promise<void>;

export function DeleteDebtor(arg1:number):Promise<void>;

export function DeleteDebtorTransaction(arg1:number):Promise<void>;

export function GetAllMerchantKeys():Promise<Array<string>>;

export function GetAvailableMonths():Promise<Array<models.AvailableMonth>>;

export function GetAvailableYears():Promise<Array<models.AvailableYear>>;

export function GetCategories():Promise<Array<models.Category>>;

export function GetCategoryRules():Promise<Array<models.CategoryRule>>;

export function GetDebtorTransactions(arg1:number):Promise<Array<models.Transaction>>;

export function GetDebtors():Promise<Array<models.DebtorDetail>>;

export function GetMerchantTransactions(arg1:string):Promise<Array<models.Transaction>>;

export function GetMonthlyStats(arg1:string):Promise<models.MonthlyStats>;

export function GetPinnedDebtors():Promise<Array<models.DebtorDetail>>;

export function GetSpendingTrend(arg1:number):Promise<Array<models.SpendingTrend>>;

export function GetTransactions(arg1:string):Promise<Array<models.Transaction>>;

export function GetUncategorizedCount():Promise<number>;

export function GetUncategorizedMerchants():Promise<Array<models.MerchantGroup>>;

export function GetYearlyStats(arg1:string):Promise<models.YearlyStats>;

export function ImportFile(arg1:string):Promise<models.ImportResult>;

export function RemoveDebtorMerchantKey(arg1:number,arg2:string):Promise<void>;

export function SearchTransactions(arg1:string,arg2:string):Promise<Array<models.Transaction>>;

export function SelectAndImportFile():Promise<models.ImportResult>;

export function ToggleDebtorPinned(arg1:number,arg2:boolean):Promise<void>;

export function UpdateCategory(arg1:number,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:boolean):Promise<void>;

export function UpdateDebtor(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateDebtorTransaction(arg1:number,arg2:string,arg3:number,arg4:string):Promise<void>;

export function UpdateTransactionCategory(arg1:number,arg2:any):Promise<void>;
