// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CategorizeByMerchant(arg1, arg2) {
  return window['go']['app']['App']['CategorizeByMerchant'](arg1, arg2);
}

export function CreateCategory(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['CreateCategory'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteCategory(arg1) {
  return window['go']['app']['App']['DeleteCategory'](arg1);
}

export function DeleteCategoryRule(arg1) {
  return window['go']['app']['App']['DeleteCategoryRule'](arg1);
}

export function GetAvailableMonths() {
  return window['go']['app']['App']['GetAvailableMonths']();
}

export function GetCategories() {
  return window['go']['app']['App']['GetCategories']();
}

export function GetCategoryRules() {
  return window['go']['app']['App']['GetCategoryRules']();
}

export function GetMerchantTransactions(arg1) {
  return window['go']['app']['App']['GetMerchantTransactions'](arg1);
}

export function GetMonthlyStats(arg1) {
  return window['go']['app']['App']['GetMonthlyStats'](arg1);
}

export function GetSpendingTrend(arg1) {
  return window['go']['app']['App']['GetSpendingTrend'](arg1);
}

export function GetTransactions(arg1) {
  return window['go']['app']['App']['GetTransactions'](arg1);
}

export function GetUncategorizedCount() {
  return window['go']['app']['App']['GetUncategorizedCount']();
}

export function GetUncategorizedMerchants() {
  return window['go']['app']['App']['GetUncategorizedMerchants']();
}

export function ImportFile(arg1) {
  return window['go']['app']['App']['ImportFile'](arg1);
}

export function SearchTransactions(arg1, arg2) {
  return window['go']['app']['App']['SearchTransactions'](arg1, arg2);
}

export function SelectAndImportFile() {
  return window['go']['app']['App']['SelectAndImportFile']();
}

export function UpdateCategory(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['UpdateCategory'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateTransactionCategory(arg1, arg2) {
  return window['go']['app']['App']['UpdateTransactionCategory'](arg1, arg2);
}
